// Step-by-step tutorial cues for common exercises.
// Pattern-match an exercise name to a short, beginner-friendly 3-5 step guide.
// Order matters — most specific patterns first.

type StepEntry = { match: RegExp; steps: string[] };

const LIBRARY: StepEntry[] = [
  // ───── Chest ─────
  { match: /incline.*(bench|press|dumbbell)/i, steps: [
    "Set bench to 30–45° incline, feet flat on floor.",
    "Hold dumbbells at shoulder height, palms forward.",
    "Press up until arms lock, dumbbells nearly touching.",
    "Lower with control to chest level — pause briefly.",
    "Repeat. Keep shoulder blades pinned to bench.",
  ]},
  { match: /decline.*(bench|press)/i, steps: [
    "Set bench to slight decline; secure feet under pads.",
    "Grip bar slightly wider than shoulders.",
    "Unrack and lower bar to lower chest.",
    "Press up explosively until arms are straight.",
    "Repeat — keep elbows tucked ~60°.",
  ]},
  { match: /dumbbell.*(bench|chest)\s*press|bench\s*press/i, steps: [
    "Lie back, plant feet, retract shoulder blades.",
    "Hold weights at chest, palms forward, elbows ~45°.",
    "Press straight up until arms lock out.",
    "Lower under control to upper-chest level.",
    "Keep wrists stacked over elbows the whole time.",
  ]},
  { match: /chest\s*fly|pec\s*fly|cable\s*fly|crossover/i, steps: [
    "Stand or lie with arms wide, slight elbow bend.",
    "Brace core; keep that elbow angle locked.",
    "Bring hands together in a wide arc.",
    "Squeeze chest hard at the top for 1 second.",
    "Reverse slowly — feel the stretch, don't drop.",
  ]},
  { match: /diamond\s*push/i, steps: [
    "Place hands together under chest, thumbs touching.",
    "Set body in a straight plank line.",
    "Lower chest to hands, elbows tracking back.",
    "Push up until arms are fully extended.",
    "Keep core tight — no sagging hips.",
  ]},
  { match: /pike\s*push/i, steps: [
    "Start in downward-dog: hips high, hands shoulder-width.",
    "Bend elbows, lower head toward the floor.",
    "Stop just before your head touches.",
    "Press back up to start, locking elbows.",
    "Keep hips high — this targets shoulders.",
  ]},
  { match: /push[-\s]?up/i, steps: [
    "Hands under shoulders, body in a straight line.",
    "Brace core, squeeze glutes — no sag.",
    "Lower chest to within an inch of the floor.",
    "Press back up explosively to start position.",
    "Breathe in on the way down, out on the press.",
  ]},

  // ───── Shoulders ─────
  { match: /arnold\s*press/i, steps: [
    "Sit upright, dumbbells at chin, palms facing you.",
    "Press up while rotating palms to face forward.",
    "Lock out overhead — biceps near ears.",
    "Reverse the rotation as you lower to start.",
    "Keep core tight, no arching the lower back.",
  ]},
  { match: /(overhead|shoulder)\s*press|ohp/i, steps: [
    "Stand tall, bar at upper chest, grip just outside shoulders.",
    "Brace abs and glutes hard — full body tension.",
    "Press bar straight up overhead, head moves through.",
    "Lock out with bar over mid-foot.",
    "Lower under control back to the front rack.",
  ]},
  { match: /lateral\s*raise/i, steps: [
    "Stand tall, dumbbells at sides, slight elbow bend.",
    "Lead with elbows, raise arms out to the sides.",
    "Stop when arms are parallel to floor.",
    "Pause 1 sec, then lower slowly to start.",
    "Don't swing — let the side delts do the work.",
  ]},
  { match: /front\s*raise/i, steps: [
    "Hold dumbbells in front of thighs, palms down.",
    "Keep arms nearly straight, slight elbow bend.",
    "Raise weights forward to shoulder height.",
    "Pause briefly — squeeze front delts.",
    "Lower under control. No body english.",
  ]},
  { match: /rear\s*delt|reverse\s*fly/i, steps: [
    "Hinge forward at hips, back flat, dumbbells hanging.",
    "Slight bend in elbows; squeeze shoulder blades.",
    "Raise arms out wide until parallel to floor.",
    "Pause hard at the top — squeeze rear delts.",
    "Lower with control — keep torso still.",
  ]},
  { match: /face\s*pull/i, steps: [
    "Set cable at face height with rope attachment.",
    "Grip rope thumbs-up; step back for tension.",
    "Pull rope to your face, elbows high and wide.",
    "Externally rotate — show your biceps at the top.",
    "Slow controlled return; keep tension throughout.",
  ]},
  { match: /shrug/i, steps: [
    "Stand tall holding weights at your sides.",
    "Keep arms straight and chest up.",
    "Lift shoulders straight up toward your ears.",
    "Squeeze hard at the top for 1 second.",
    "Lower with control — don't roll the shoulders.",
  ]},
  { match: /handstand/i, steps: [
    "Face a wall; place hands shoulder-width, ~10cm out.",
    "Kick one leg up, then the other, to vertical.",
    "Heels rest lightly on the wall, body stacked.",
    "Squeeze glutes, point toes, look between hands.",
    "Hold for time — step down one leg at a time.",
  ]},

  // ───── Back ─────
  { match: /pull[-\s]?up/i, steps: [
    "Grip bar slightly wider than shoulders, palms away.",
    "Hang with arms straight, shoulder blades engaged.",
    "Pull chest toward the bar — drive elbows down.",
    "Chin clears the bar at the top.",
    "Lower under control to a full hang. Repeat.",
  ]},
  { match: /chin[-\s]?up/i, steps: [
    "Grip bar shoulder-width, palms facing you.",
    "Hang with arms straight, core tight.",
    "Pull yourself up, leading with the chest.",
    "Chin clears the bar; squeeze biceps and back.",
    "Lower under full control to a dead hang.",
  ]},
  { match: /lat\s*pull|pulldown/i, steps: [
    "Sit, secure thighs, grip bar wider than shoulders.",
    "Lean back ~10°, chest up, shoulders down.",
    "Pull bar to upper chest, driving elbows down.",
    "Squeeze lats hard at the bottom.",
    "Return slowly until arms fully extend overhead.",
  ]},
  { match: /t[-\s]?bar\s*row/i, steps: [
    "Straddle the bar, hinge to ~45°, flat back.",
    "Grip handles, arms hanging straight.",
    "Pull weight to lower chest, elbows tucked.",
    "Squeeze shoulder blades together at the top.",
    "Lower until arms straight; keep torso angle.",
  ]},
  { match: /seated\s*(cable\s*)?row/i, steps: [
    "Sit tall, feet on platform, slight knee bend.",
    "Grip handle; chest up, shoulders back.",
    "Pull handle to your belly, elbows back.",
    "Squeeze mid-back hard for 1 second.",
    "Extend arms slowly — no rounding the back.",
  ]},
  { match: /one[-\s]?arm.*row|single[-\s]?arm.*row/i, steps: [
    "Brace one knee and hand on a bench.",
    "Hold dumbbell, arm hanging straight down.",
    "Row weight to your hip, elbow tight to side.",
    "Squeeze lat at the top — don't twist torso.",
    "Lower under control, full stretch at bottom.",
  ]},
  { match: /inverted\s*row/i, steps: [
    "Set bar at hip height; lie under it.",
    "Grip overhand, body straight, heels on floor.",
    "Pull chest to the bar, elbows back ~45°.",
    "Squeeze shoulder blades at the top.",
    "Lower with control to full arm extension.",
  ]},
  { match: /(bent.*over\s*)?row/i, steps: [
    "Hinge at hips to ~45°, flat back, knees soft.",
    "Hold bar with overhand grip, arms hanging.",
    "Row bar to lower chest/upper belly.",
    "Pause and squeeze shoulder blades.",
    "Lower under control — keep torso angle locked.",
  ]},
  { match: /superman/i, steps: [
    "Lie face down, arms extended overhead.",
    "Brace glutes and lower back.",
    "Lift arms, chest, and legs off the floor.",
    "Hold the top position for 2 seconds.",
    "Lower slowly. Keep neck neutral throughout.",
  ]},

  // ───── Legs ─────
  { match: /goblet\s*squat/i, steps: [
    "Hold one dumbbell vertical at your chest.",
    "Feet shoulder-width, toes slightly out.",
    "Sit hips back and down — chest up, elbows in.",
    "Descend until thighs are parallel or below.",
    "Drive through heels to stand. Repeat.",
  ]},
  { match: /front\s*squat/i, steps: [
    "Bar racks on front delts, elbows high.",
    "Feet shoulder-width, brace core hard.",
    "Squat down keeping torso vertical.",
    "Hit depth — thighs at or below parallel.",
    "Drive up through mid-foot, elbows stay up.",
  ]},
  { match: /bulgarian\s*split/i, steps: [
    "Place rear foot on bench, front foot ~2 ft ahead.",
    "Hold weights at sides, torso slightly forward.",
    "Lower until front thigh is parallel to floor.",
    "Drive through front heel to stand.",
    "Finish all reps one side, then switch.",
  ]},
  { match: /pistol\s*squat/i, steps: [
    "Stand on one leg, other leg out in front.",
    "Arms forward for counterbalance, chest up.",
    "Sit back and down on the working leg.",
    "Reach bottom — hamstring on calf if possible.",
    "Drive up through heel without losing balance.",
  ]},
  { match: /jump\s*squat/i, steps: [
    "Stand feet shoulder-width, arms at sides.",
    "Drop into a quarter squat, swing arms back.",
    "Explode up — jump as high as you can.",
    "Land softly through midfoot, knees over toes.",
    "Absorb into next rep — quiet feet.",
  ]},
  { match: /sumo\s*deadlift/i, steps: [
    "Stand wide, toes turned out ~30°, bar over mid-foot.",
    "Grip inside legs, hips down, chest up.",
    "Push the floor away — bar slides up legs.",
    "Lock out hips and knees at the top together.",
    "Reverse the path back to the floor.",
  ]},
  { match: /sumo\s*squat/i, steps: [
    "Take a wide stance, toes pointed out.",
    "Hold weight at chest or between legs.",
    "Sit straight down, knees tracking over toes.",
    "Reach parallel; keep torso upright.",
    "Drive up through heels, squeeze glutes.",
  ]},
  { match: /squat/i, steps: [
    "Feet shoulder-width, toes slightly out.",
    "Brace core, chest up, eyes forward.",
    "Sit hips back and down between your heels.",
    "Reach parallel or below if mobility allows.",
    "Drive through whole foot to stand.",
  ]},
  { match: /romanian|rdl/i, steps: [
    "Stand tall holding bar at hips, soft knees.",
    "Hinge hips back — bar slides down thighs.",
    "Stop when you feel a deep hamstring stretch.",
    "Drive hips forward to stand tall again.",
    "Keep back flat the entire movement.",
  ]},
  { match: /deadlift/i, steps: [
    "Bar over mid-foot, shins ~1 inch from bar.",
    "Hinge and grip just outside knees.",
    "Chest up, lats tight, back flat.",
    "Push the floor away — bar drags up legs.",
    "Lock hips at the top; reverse to the floor.",
  ]},
  { match: /walking\s*lunge/i, steps: [
    "Stand tall holding weights at your sides.",
    "Step forward into a long lunge stance.",
    "Lower until back knee hovers above floor.",
    "Drive through front heel into the next step.",
    "Alternate legs — keep torso upright throughout.",
  ]},
  { match: /reverse\s*lunge/i, steps: [
    "Stand tall, hands on hips or holding weights.",
    "Step one foot back into a long stance.",
    "Lower until back knee nearly touches floor.",
    "Drive through front heel back to standing.",
    "Alternate legs. Keep chest tall.",
  ]},
  { match: /lunge/i, steps: [
    "Stand tall, feet hip-width apart.",
    "Step forward into a long stance.",
    "Lower back knee toward the ground.",
    "Push through front heel to return to start.",
    "Alternate legs — torso stays vertical.",
  ]},
  { match: /step[-\s]?up/i, steps: [
    "Stand facing a sturdy box at knee height.",
    "Place full foot on box; weights at sides.",
    "Drive through that heel to stand on top.",
    "Stand fully tall, then step back down.",
    "Complete reps one leg, then switch.",
  ]},
  { match: /leg\s*press/i, steps: [
    "Sit back, feet shoulder-width on platform.",
    "Release safeties; keep lower back planted.",
    "Lower platform until knees reach 90°.",
    "Press back up; don't lock knees out hard.",
    "Control the eccentric — no bouncing.",
  ]},
  { match: /leg\s*extension/i, steps: [
    "Sit back, pad on top of lower shins.",
    "Grip handles; keep hips on the seat.",
    "Extend knees fully — squeeze quads at top.",
    "Pause 1 sec, then lower under control.",
    "No swinging — quads do all the work.",
  ]},
  { match: /leg\s*curl|hamstring\s*curl/i, steps: [
    "Lie face down, pad just above your heels.",
    "Grip handles; hips pinned to the bench.",
    "Curl heels toward your glutes.",
    "Squeeze hamstrings hard at the top.",
    "Lower slowly to a full stretch.",
  ]},
  { match: /hip\s*thrust|glute\s*bridge/i, steps: [
    "Upper back on bench, weight across hips.",
    "Feet flat, knees over ankles.",
    "Drive through heels — hips up to a tabletop.",
    "Squeeze glutes hard for 1 second.",
    "Lower with control without dropping.",
  ]},
  { match: /calf\s*raise|calves/i, steps: [
    "Stand with balls of feet on edge of step.",
    "Heels hang down; brace core.",
    "Press up onto your toes as high as possible.",
    "Hold the top, squeeze calves for 1 second.",
    "Lower until you feel a deep calf stretch.",
  ]},
  { match: /wall\s*sit/i, steps: [
    "Stand back-against-wall, feet 2 ft out.",
    "Slide down until thighs are parallel to floor.",
    "Knees stacked over ankles, 90° angle.",
    "Hands off thighs — arms rest at sides.",
    "Hold for time. Breathe steady.",
  ]},

  // ───── Arms ─────
  { match: /hammer\s*curl/i, steps: [
    "Stand tall, dumbbells at sides, palms inward.",
    "Keep elbows pinned to your ribs.",
    "Curl weights up keeping palms facing in.",
    "Squeeze biceps and forearms at the top.",
    "Lower under control — no swinging.",
  ]},
  { match: /preacher\s*curl/i, steps: [
    "Sit, arms on the preacher pad, slight bend in elbows.",
    "Grip bar shoulder-width, palms up.",
    "Curl weight up toward your shoulders.",
    "Squeeze biceps at the top.",
    "Lower slowly to nearly straight — don't bounce.",
  ]},
  { match: /barbell\s*curl|curl/i, steps: [
    "Stand tall, grip bar shoulder-width, palms up.",
    "Pin elbows to your sides, chest up.",
    "Curl bar up toward your shoulders.",
    "Squeeze biceps hard at the top.",
    "Lower under control — full extension at bottom.",
  ]},
  { match: /skull\s*crusher|lying\s*tricep/i, steps: [
    "Lie on bench, hold bar over chest, arms straight.",
    "Lock upper arms vertical — only elbows move.",
    "Lower bar toward forehead under control.",
    "Press back up by extending the elbows.",
    "Keep upper arms still the entire time.",
  ]},
  { match: /tricep\s*pushdown|rope\s*pushdown/i, steps: [
    "Face cable, rope at chest height, elbows tucked.",
    "Grip rope thumbs up; chest up, lean slightly.",
    "Push down by extending elbows fully.",
    "Spread rope at the bottom — squeeze triceps.",
    "Return slowly; keep elbows pinned to sides.",
  ]},
  { match: /tricep|dip/i, steps: [
    "Grip bars or bench edge; arms straight.",
    "Lean slightly forward; legs supported or hanging.",
    "Lower until elbows reach about 90°.",
    "Press back up to lock-out.",
    "Keep elbows tracking back, not flaring out.",
  ]},

  // ───── Core ─────
  { match: /plank/i, steps: [
    "Forearms on floor, elbows under shoulders.",
    "Body in one straight line, toes tucked.",
    "Squeeze glutes and brace abs hard.",
    "Don't let hips sag or pike up.",
    "Hold and breathe steady for time.",
  ]},
  { match: /russian\s*twist/i, steps: [
    "Sit, lean back ~45°, knees bent, feet up.",
    "Hold weight or hands clasped at chest.",
    "Rotate torso to one side, tap weight down.",
    "Rotate to the other side under control.",
    "Keep chest up — don't round the back.",
  ]},
  { match: /bicycle/i, steps: [
    "Lie on back, hands lightly behind head.",
    "Lift shoulders off the floor; legs in tabletop.",
    "Bring opposite elbow to opposite knee.",
    "Extend the other leg out fully.",
    "Alternate slowly with twist through obliques.",
  ]},
  { match: /hanging.*knee|hanging.*leg|leg\s*raise/i, steps: [
    "Hang from bar, shoulders engaged.",
    "Brace abs — no swinging.",
    "Raise knees (or straight legs) toward chest.",
    "Pause at the top — feel the abs squeeze.",
    "Lower slowly back to a dead hang.",
  ]},
  { match: /v[-\s]?up/i, steps: [
    "Lie flat, arms extended overhead, legs straight.",
    "Simultaneously lift legs and torso.",
    "Reach hands toward toes — form a V.",
    "Pause briefly at the top.",
    "Lower with control to start without touching down.",
  ]},
  { match: /sit[-\s]?up/i, steps: [
    "Lie back, knees bent, feet flat on floor.",
    "Hands across chest or by ears.",
    "Curl up one vertebra at a time.",
    "Sit fully up; pause briefly at the top.",
    "Lower slowly back to the start.",
  ]},
  { match: /crunch|abs/i, steps: [
    "Lie back, knees bent, feet flat.",
    "Hands lightly behind head — don't pull neck.",
    "Curl shoulder blades off the floor.",
    "Squeeze abs hard at the top for 1 second.",
    "Lower slowly to start. Repeat.",
  ]},
  { match: /dead\s*bug/i, steps: [
    "Lie on back, arms up, knees over hips at 90°.",
    "Press lower back into the floor.",
    "Lower opposite arm and leg slowly to floor.",
    "Return to start without losing back contact.",
    "Alternate sides — slow, controlled reps.",
  ]},
  { match: /hollow\s*hold|hollow\s*body/i, steps: [
    "Lie on back, arms overhead, legs straight.",
    "Press lower back into the floor.",
    "Lift arms, head, and legs a few inches up.",
    "Body should look like a banana — abs braced.",
    "Hold for time, breathing shallow but steady.",
  ]},

  // ───── Conditioning / Olympic ─────
  { match: /burpee/i, steps: [
    "Stand tall; drop hands to floor.",
    "Kick feet back into a plank position.",
    "Do a push-up (optional), then jump feet in.",
    "Explode up into a jump, hands overhead.",
    "Land soft and immediately repeat.",
  ]},
  { match: /mountain\s*climber/i, steps: [
    "Start in a high plank — hands under shoulders.",
    "Brace core; keep hips low and level.",
    "Drive one knee toward your chest fast.",
    "Switch legs in a quick, smooth rhythm.",
    "Don't bounce hips — keep the plank shape.",
  ]},
  { match: /jumping\s*jack/i, steps: [
    "Stand tall, feet together, arms at sides.",
    "Jump feet wide while raising arms overhead.",
    "Clap or touch hands at the top.",
    "Jump feet back together, arms back down.",
    "Keep a steady rhythm; land softly.",
  ]},
  { match: /high\s*knee/i, steps: [
    "Stand tall, feet hip-width apart.",
    "Run in place, driving knees up to hip height.",
    "Pump arms in opposition — fast tempo.",
    "Stay on the balls of your feet.",
    "Keep core tight, chest up the whole time.",
  ]},
  { match: /(jump\s*rope|skip)/i, steps: [
    "Hold rope handles at hips, elbows tucked.",
    "Spin rope from the wrists — not the arms.",
    "Hop on balls of feet, just clearing the rope.",
    "Stay light — quiet, low jumps.",
    "Find a steady rhythm and breathe.",
  ]},
  { match: /box\s*jump/i, steps: [
    "Stand a foot back from the box.",
    "Hinge slightly, swing arms back.",
    "Explode up and forward onto the box.",
    "Land softly in a quarter-squat position.",
    "Stand tall on top, step back down.",
  ]},
  { match: /kettlebell\s*swing/i, steps: [
    "Stand over the kettlebell, hinge to grip it.",
    "Hike it back between your legs hard.",
    "Snap hips forward to drive bell to chest height.",
    "Let it fall — re-hinge on the way down.",
    "Power comes from hips, not arms.",
  ]},
  { match: /clean.*jerk|clean\s*and\s*jerk/i, steps: [
    "Set up like a deadlift, bar over mid-foot.",
    "Pull explosively, shrug, then drop under bar.",
    "Catch in a front rack; stand up tall.",
    "Dip and drive bar overhead, splitting feet.",
    "Recover feet under bar, lock out overhead.",
  ]},
  { match: /power\s*clean|clean/i, steps: [
    "Bar over mid-foot, grip just outside knees.",
    "Lift bar from floor, accelerate past knees.",
    "Triple extend — jump and shrug hard.",
    "Drop under and catch in a quarter front squat.",
    "Stand tall to finish the rep.",
  ]},
  { match: /snatch/i, steps: [
    "Wide grip on bar, hips down, chest up.",
    "Lift, then explode through the hips.",
    "Pull bar high while dropping under it.",
    "Catch overhead in a squat, arms locked.",
    "Stand up tall to complete.",
  ]},
  { match: /thruster/i, steps: [
    "Hold weight in front rack, feet shoulder-width.",
    "Squat down to full depth.",
    "Drive up explosively out of the squat.",
    "Use the momentum to press weight overhead.",
    "Lock out arms; lower back to rack and repeat.",
  ]},
  { match: /farmer/i, steps: [
    "Hold heavy weights at your sides.",
    "Stand tall — chest up, shoulders back.",
    "Walk in a straight line with short steps.",
    "Brace core; don't let weights swing.",
    "Walk for distance or time — set them down softly.",
  ]},
  { match: /bear\s*crawl/i, steps: [
    "Get on hands and knees, knees just off floor.",
    "Back flat — hover position, core braced.",
    "Move opposite hand and foot together.",
    "Keep hips level — don't sway.",
    "Crawl for distance or time, then reverse.",
  ]},
];

// Generic fallback steps that work for nearly any movement.
const GENERIC_STEPS = [
  "Set up with a stable, balanced stance.",
  "Brace your core and engage the working muscles.",
  "Move through the full range of motion under control.",
  "Pause briefly at the peak contraction.",
  "Return slowly to the start position. Repeat.",
];

export function exerciseSteps(name: string): string[] {
  for (const entry of LIBRARY) {
    if (entry.match.test(name)) return entry.steps;
  }
  return GENERIC_STEPS;
}
