// Maps a food/ingredient string to an emoji. Used in meal cards.
const MAP: [RegExp, string][] = [
  [/egg/i, "🥚"],
  [/oat|granola|cereal/i, "🥣"],
  [/chicken|poultry/i, "🍗"],
  [/beef|steak|burger/i, "🥩"],
  [/pork|bacon|ham/i, "🥓"],
  [/fish|salmon|tuna|cod|tilapia/i, "🐟"],
  [/shrimp|prawn|seafood/i, "🦐"],
  [/rice/i, "🍚"],
  [/pasta|spaghetti|noodle/i, "🍝"],
  [/bread|toast|bagel|bun/i, "🍞"],
  [/potato|fries/i, "🥔"],
  [/sweet\s*potato|yam/i, "🍠"],
  [/avocado/i, "🥑"],
  [/broccoli/i, "🥦"],
  [/carrot/i, "🥕"],
  [/corn/i, "🌽"],
  [/tomato/i, "🍅"],
  [/pepper|capsicum|chili/i, "🌶️"],
  [/onion|garlic/i, "🧅"],
  [/cucumber|pickle/i, "🥒"],
  [/lettuce|spinach|kale|salad|green/i, "🥬"],
  [/mushroom/i, "🍄"],
  [/cheese|parmesan|feta|mozz/i, "🧀"],
  [/milk|yogurt|yoghurt|kefir/i, "🥛"],
  [/butter/i, "🧈"],
  [/almond|walnut|cashew|nut|peanut/i, "🥜"],
  [/bean|lentil|chickpea|tofu|tempeh/i, "🫘"],
  [/apple/i, "🍎"],
  [/banana/i, "🍌"],
  [/berry|strawberr|blueberr|raspberr/i, "🍓"],
  [/grape/i, "🍇"],
  [/orange|citrus/i, "🍊"],
  [/lemon|lime/i, "🍋"],
  [/mango/i, "🥭"],
  [/pineapple/i, "🍍"],
  [/honey|syrup|sugar/i, "🍯"],
  [/oil|olive/i, "🫒"],
  [/coffee|espresso/i, "☕"],
  [/tea/i, "🍵"],
  [/water/i, "💧"],
  [/protein|shake|whey/i, "🥤"],
  [/chocolate|cocoa/i, "🍫"],
  [/salt|spice|herb/i, "🧂"],
];

export function foodEmoji(item: string): string {
  for (const [re, emoji] of MAP) if (re.test(item)) return emoji;
  return "🍽️";
}
