// 100+ rotating quotes for the Home marquee.
// Picked daily by date, but a `getRandomQuote()` is also exposed.

export type Quote = { text: string; author: string };

export const QUOTES: Quote[] = [
  { text: "You don't rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "Pressure is a privilege.", author: "Billie Jean King" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "It never gets easier, you just get better.", author: "Jordan Hoechlin" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
  { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "I hated every minute of training, but I said: don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Sweat is just fat crying.", author: "Unknown" },
  { text: "If it doesn't challenge you, it won't change you.", author: "Fred DeVito" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Your only limit is you.", author: "Unknown" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "Once you learn to quit, it becomes a habit.", author: "Vince Lombardi" },
  { text: "The clock is ticking. Are you becoming the person you want to be?", author: "Greg Plitt" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "George Lorimer" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Dream bigger. Do bigger.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins" },
  { text: "Stay hard.", author: "David Goggins" },
  { text: "You are stronger than you think.", author: "Unknown" },
  { text: "What hurts today makes you stronger tomorrow.", author: "Jay Cutler" },
  { text: "Make sweat your best accessory.", author: "Unknown" },
  { text: "Be the energy you want to attract.", author: "Unknown" },
  { text: "If you want something you've never had, you must do something you've never done.", author: "Thomas Jefferson" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "A year from now you'll wish you had started today.", author: "Karen Lamb" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Robin Sharma" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't — you're right.", author: "Henry Ford" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Be stronger than your strongest excuse.", author: "Unknown" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "The mind is the limit. As long as the mind can envision it, you can do it.", author: "Arnold Schwarzenegger" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "First we form habits, then they form us. Conquer your bad habits or they'll conquer you.", author: "Rob Gilbert" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "If you fail to prepare, you're prepared to fail.", author: "Mark Spitz" },
  { text: "It's not about being the best. It's about being better than yesterday.", author: "Unknown" },
  { text: "The will to win means nothing without the will to prepare.", author: "Juma Ikangaa" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "I can accept failure. Everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "You have to expect things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "Talent wins games, but teamwork and intelligence win championships.", author: "Michael Jordan" },
  { text: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett" },
  { text: "The difference between the impossible and the possible lies in determination.", author: "Tommy Lasorda" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Excuses don't burn calories.", author: "Unknown" },
  { text: "If you don't make time for your wellness, you will be forced to make time for your illness.", author: "Joyce Sunada" },
  { text: "Train insane or remain the same.", author: "Jillian Michaels" },
  { text: "The body is your slave; it works for you.", author: "Jack LaLanne" },
  { text: "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.", author: "Jack LaLanne" },
  { text: "If it's important to you, you'll find a way. If not, you'll find an excuse.", author: "Unknown" },
  { text: "Your body can stand almost anything. It's your mind you have to convince.", author: "Unknown" },
  { text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Today I will do what others won't, so tomorrow I can do what others can't.", author: "Jerry Rice" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "It's a slow process, but quitting won't speed it up.", author: "Unknown" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "We may encounter many defeats, but we must not be defeated.", author: "Maya Angelou" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "It's hard to beat a person who never gives up.", author: "Babe Ruth" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
  { text: "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.", author: "Rikki Rogers" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Embrace the suck.", author: "Unknown" },
  { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "Jim Rohn" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "Easy is earned.", author: "Unknown" },
  { text: "Be obsessed or be average.", author: "Grant Cardone" },
  { text: "Hustle in silence and let your success make the noise.", author: "Unknown" },
  { text: "Doing the best at this moment puts you in the best place for the next moment.", author: "Oprah Winfrey" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "Don't be afraid to fail. Be afraid not to try.", author: "Michael Jordan" },
  { text: "Get comfortable being uncomfortable.", author: "Unknown" },
  { text: "Self-belief and hard work will always earn you success.", author: "Virat Kohli" },
  { text: "When you feel like quitting, think about why you started.", author: "Unknown" },
  { text: "Energy flows where attention goes.", author: "Tony Robbins" },
  { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
  { text: "Slow is smooth. Smooth is fast.", author: "Navy SEALs" },
  { text: "Beneath every behavior there is a feeling. Beneath every feeling there is a need.", author: "Unknown" },
  { text: "You are one workout away from a good mood.", author: "Unknown" },
  { text: "Just do it.", author: "Nike" },
  { text: "Impossible is just an opinion.", author: "Paulo Coelho" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "The man on top of the mountain didn't fall there.", author: "Vince Lombardi" },
  { text: "Inhale courage. Exhale fear.", author: "Unknown" },
  { text: "Showing up is half the battle.", author: "Woody Allen" },

  // ───────────── Famous athletes & coaches ─────────────
  { text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "You can't put a limit on anything. The more you dream, the farther you get.", author: "Michael Phelps" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.", author: "Muhammad Ali" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "It's not the will to win that matters — everyone has that. It's the will to prepare to win that matters.", author: "Paul 'Bear' Bryant" },
  { text: "The price of success is hard work, dedication to the job at hand.", author: "Vince Lombardi" },
  { text: "Winners never quit, and quitters never win.", author: "Vince Lombardi" },
  { text: "You're never really playing an opponent. You're playing yourself.", author: "Arthur Ashe" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "I trained four years to run nine seconds, and people give up when they don't see results in two months.", author: "Usain Bolt" },
  { text: "Persistence can change failure into extraordinary achievement.", author: "Matt Biondi" },
  { text: "Today's accomplishments were yesterday's impossibilities.", author: "Robert H. Schuller" },
  { text: "Iron sharpens iron.", author: "King Solomon" },
  { text: "Everybody wants to be a beast, until it's time to do what real beasts do.", author: "Eric Thomas" },
  { text: "When you want to succeed as bad as you want to breathe, then you'll be successful.", author: "Eric Thomas" },
  { text: "Pain is weakness leaving the body.", author: "Lt. Gen. Lewis 'Chesty' Puller" },
  { text: "The only easy day was yesterday.", author: "Navy SEALs" },

  // ───────────── Bodybuilding / strength legends ─────────────
  { text: "The last three or four reps is what makes the muscle grow.", author: "Arnold Schwarzenegger" },
  { text: "There is no magic pill. The only way to get fit is hard work.", author: "Arnold Schwarzenegger" },
  { text: "If you can count your reps, you didn't go heavy enough.", author: "Ronnie Coleman" },
  { text: "Everybody wants to be a bodybuilder, but nobody wants to lift no heavy-ass weights.", author: "Ronnie Coleman" },
  { text: "Yeah buddy, light weight baby!", author: "Ronnie Coleman" },
  { text: "Set goals so big that you can't achieve them until you grow into the person who can.", author: "C.T. Fletcher" },
  { text: "I command you to grow!", author: "C.T. Fletcher" },
  { text: "Strength is the product of struggle.", author: "Henry Rollins" },
  { text: "The iron never lies to you.", author: "Henry Rollins" },
  { text: "Don't be afraid of failure. This is the way to succeed.", author: "LeBron James" },
  { text: "I've never been afraid of big moments.", author: "LeBron James" },
  { text: "The most important thing is to try and inspire people so that they can be great in whatever they want to do.", author: "Kobe Bryant" },
  { text: "Great things come from hard work and perseverance. No excuses.", author: "Kobe Bryant" },
  { text: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", author: "Kobe Bryant" },
  { text: "Mamba mentality is all about focusing on the process.", author: "Kobe Bryant" },
  { text: "I'm not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },

  // ───────────── Endurance, climbers & adventurers ─────────────
  { text: "Because it's there.", author: "George Mallory" },
  { text: "Get busy living, or get busy dying.", author: "Stephen King" },
  { text: "Run when you can, walk if you have to, crawl if you must; just never give up.", author: "Dean Karnazes" },
  { text: "Somewhere behind the athlete you've become is a kid who fell in love with the game. Play for her.", author: "Mia Hamm" },
  { text: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },

  // ───────────── Philosophers & ancient wisdom ─────────────
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "Out of suffering have emerged the strongest souls.", author: "Khalil Gibran" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },

  // ───────────── Martial arts ─────────────
  { text: "Be like water making its way through cracks.", author: "Bruce Lee" },
  { text: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
  { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },

  // ───────────── Entrepreneurs & thinkers ─────────────
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
  { text: "Failure is an option here. If things are not failing, you are not innovating enough.", author: "Elon Musk" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "Genius is one percent inspiration, ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },

  // ───────────── Leaders & changemakers ─────────────
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "If you can't fly then run, if you can't run then walk, but whatever you do, keep moving forward.", author: "Martin Luther King Jr." },

  // ───────────── Modern motivators ─────────────
  { text: "Who's going to carry the boats?!", author: "David Goggins" },
  { text: "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", author: "David Goggins" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "You become what you think about most of the time.", author: "Earl Nightingale" },
  { text: "Most people overestimate what they can do in one year and underestimate what they can do in ten years.", author: "Bill Gates" },
  { text: "Whatever the mind can conceive and believe, it can achieve.", author: "Napoleon Hill" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
];

/** Pick a deterministic quote based on day-of-year. */
export function getDailyQuote(d = new Date()): Quote {
  const start = new Date(d.getFullYear(), 0, 0);
  const day = Math.floor((d.getTime() - start.getTime()) / 86_400_000);
  return QUOTES[day % QUOTES.length];
}

/** Pick a random quote (uniform). */
export function getRandomQuote(): Quote {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
